export const SET_WEAPON_TYPE = "SET_WEAPON_TYPE";
export const SET_WEAPON = "SET_WEAPON";
export const SET_HELMET = "SET_HELMET";
export const SET_VEST = "SET_VEST";
export const SET_VIEW = "SET_VIEW";
export const SET_CURRENT_PROPS = "SET_CURRENT_PROPS";
export const SET_BACKDROP_STATE = "SET_BACKDROP_STATE";
export const SET_RIGHT_TOOLS_STATE = "SET_RIGHT_TOOLS_STATE";
